name: RSpec

on:
  pull_request:

jobs:
  rspec:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: [2.4, 2.5, 2.6, 2.7]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
          gem install bundler
      - run: |
          bundle install --jobs 4 --retry 3
      - run: |
          bundle exec rspec
