name: RuboCop

on:
  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.4.x
      - run: |
          gem install bundler
      - run: |
          bundle install --gemfile gemfiles/rubocop.gemfile --jobs 4 --retry 3
      - run: |
          bundle exec --gemfile gemfiles/rubocop.gemfile rubocop
